PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE Cars(Id integer PRIMARY KEY, Name text, Cost integer);
INSERT INTO "Cars" VALUES(1,'Audi',52642);
INSERT INTO "Cars" VALUES(2,'Mercedes',57127);
INSERT INTO "Cars" VALUES(3,'Skoda',9000);
INSERT INTO "Cars" VALUES(4,'Volvo',29000);
INSERT INTO "Cars" VALUES(5,'Bentley',350000);
INSERT INTO "Cars" VALUES(6,'Citroen',21000);
INSERT INTO "Cars" VALUES(7,'Hummer',41400);
INSERT INTO "Cars" VALUES(8,'Volkswagen',21600);
CREATE TABLE Orders(Id integer PRIMARY KEY, OrderPrice integer CHECK(OrderPrice>0), Customer text);
INSERT INTO "Orders" VALUES(1,1200,'Williamson');
INSERT INTO "Orders" VALUES(2,200,'Robertson');
INSERT INTO "Orders" VALUES(3,40,'Robertson');
INSERT INTO "Orders" VALUES(4,1640,'Smith');
INSERT INTO "Orders" VALUES(5,100,'Robertson');
INSERT INTO "Orders" VALUES(6,50,'Williamson');
INSERT INTO "Orders" VALUES(7,150,'Smith');
INSERT INTO "Orders" VALUES(8,250,'Smith');
INSERT INTO "Orders" VALUES(9,840,'Brown');
INSERT INTO "Orders" VALUES(10,440,'Black');
INSERT INTO "Orders" VALUES(11,20,'Brown');
CREATE TABLE Friends(Id integer PRIMARY KEY, Name text UNIQUE NOT NULL, Sex text CHECK(Sex IN ('M', 'F')));
INSERT INTO "Friends" VALUES(1,'Jane','F');
INSERT INTO "Friends" VALUES(2,'Thomas','M');
INSERT INTO "Friends" VALUES(3,'Franklin','M');
INSERT INTO "Friends" VALUES(4,'Elisabeth','F');
INSERT INTO "Friends" VALUES(5,'Mary','F');
INSERT INTO "Friends" VALUES(6,'Lucy','F');
INSERT INTO "Friends" VALUES(7,'Jack','M');
CREATE TABLE Customers(CustomerId integer PRIMARY KEY, Name text);
INSERT INTO "Customers" VALUES(1,'Paul Novak');
INSERT INTO "Customers" VALUES(2,'Terry Neils');
INSERT INTO "Customers" VALUES(3,'Jack Fonda');
INSERT INTO "Customers" VALUES(4,'Tom Willis');
CREATE TABLE Reservations(Id integer PRIMARY KEY, CustomerId integer, Day text);
INSERT INTO "Reservations" VALUES(1,1,'2009-22-11');
INSERT INTO "Reservations" VALUES(2,2,'2009-28-11');
INSERT INTO "Reservations" VALUES(3,2,'2009-29-11');
INSERT INTO "Reservations" VALUES(4,1,'2009-29-11');
INSERT INTO "Reservations" VALUES(5,3,'2009-02-12');
CREATE TABLE Names(Id integer, Name text);
INSERT INTO "Names" VALUES(1,'Tom');
INSERT INTO "Names" VALUES(2,'Lucy');
INSERT INTO "Names" VALUES(3,'Frank');
INSERT INTO "Names" VALUES(4,'Jane');
INSERT INTO "Names" VALUES(5,'Robert');
CREATE TABLE Books(Id integer PRIMARY KEY, Title text, Author text, Isbn text default 'not available');
INSERT INTO "Books" VALUES(1,'War and Peace','Leo Tolstoy','978-0345472403');
INSERT INTO "Books" VALUES(2,'The Brothers Karamazov','Fyodor Dostoyevsky','978-0486437910');
INSERT INTO "Books" VALUES(3,'Crime and Punishment','Fyodor Dostoyevsky','978-1840224306');
COMMIT;
